### ISSUE TITLE
Can't create project with Rails 8

### ISSUE THREAD

**Issue by wpjmurray** [rails/rails-new#39]
I'm trying to create a new Rails 8 project. Looking at the Dockerfile it checks if $RAILS_VERSION exists and uses that to install Rails. However, I've tried setting $RAILS_VERSION a few different ways and the project keeps using Rails 7.2.0. I also have Ruby 3.3.5 and Rails 8.0.0 installed globally via rbenv. How do I force the use of Rails by rails-new?

**Comment by onshi** [comment]
Hey there,

for this project you don't really need ruby and rails installed locally. 

Do you mind trying this switches with `rails-new`:

```bash
rails-new --ruby-version 3.3.5 --rails-version 8.0.0 test_app
```

it should create new rails project for you inside `test_app` directory. 

You can quickly verify if it works with this docker command

```bash
docker run -it --rm -v $(pwd)/test_app:/rails -w /rails -p 3000:3000 -e BINDING=0.0.0.0 rails-new-3.3.5-8.0.0 /bin/bash -c "bundle install && ./bin/dev"
```

```bash
open http://localhost:3000
```

lmk if this worked

cheers!

**Comment by wpjmurray** [comment]
Thank you, that worked. I was not aware of the --ruby-version and --rails-version flags, they don't appear in the rails-new documentation nor in the documentation on the Rails guides website for "rails new".
