### ISSUE TITLE
Add instalation instructions

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails-new#5]
On Mac OS because of the Gatekeeper it is better if we tell users to download using curl or any method that doesn't add the file to quarantine.

On linux user needs to be in the docker group. Maybe this requirement will change if we use http API instead of the docker CLI.

Still pending testing on windows.

**Comment by qrooel** [comment]
+1 We need some installation instructions :)

**Comment by hachi8833** [comment]
Great tool! I believe the `rails-new` tool should finally be the modern and newer official `rails new`, integrating with .devcontainer, GitHub CodeSpaces, Kamal etc.

I also found that we can pass any existing options like `-a propshaft` for `rails new` to the rails-new tool.
> except the options that refer to the local environment such as `-m`

**Comment by JoeyDoey** [comment]
> On Mac OS because of the Gatekeeper it is better if we tell users to download using curl or any method that doesn't add the file to quarantine.
> 
> On linux user needs to be in the docker group. Maybe this requirement will change if we use http API instead of the docker CLI.
> 
> Still pending testing on windows.

```shell 
 curl -L -o rails-new-aarch64-apple-darwin.tar.gz https://github.com/rails/rails-new/releases/download/v0.3.0/rails-new-aarch64-apple-darwin.tar.gz
```

```shell 
tar -xzf rails-new-aarch64-apple-darwin.tar.gz
```

```shell 
sudo mv rails-new /usr/local/bin/
```

🤙

**Comment by vitalyliber** [comment]
> > On Mac OS because of the Gatekeeper it is better if we tell users to download using curl or any method that doesn't add the file to quarantine.
> > On linux user needs to be in the docker group. Maybe this requirement will change if we use http API instead of the docker CLI.
> > Still pending testing on windows.
> 
>  curl -L -o rails-new-aarch64-apple-darwin.tar.gz https://github.com/rails/rails-new/releases/download/v0.3.0/rails-new-aarch64-apple-darwin.tar.gz
> tar -xzf rails-new-aarch64-apple-darwin.tar.gz
> sudo mv rails-new /usr/local/bin/
> rails-new --help
> ```
> A CLI tool to generate a new Rails project
> 
> Usage: rails-new [OPTIONS] <ARGS>...
>        rails-new [OPTIONS] [ARGS]... <COMMAND>
> 
> Commands:
>   rails-help  Prints `rails new --help`
>   help        Print this message or the help of the given subcommand(s)
> 
> Arguments:
>   <ARGS>...  arguments passed to `rails new`
> 
> Options:
>   -u, --ruby-version <RUBY_VERSION>    [default: 3.3.1]
>   -r, --rails-version <RAILS_VERSION>  [default: 7.1.3]
>   -h, --help                           Print help
>   -V, --version                        Print version
> ```
> 
> 🤙

It should be in the Readme 👍
